### ISSUE TITLE
BUG-32 !class <name> level=None doesn't work anymore

### ISSUE THREAD

**Issue by crawltracker** [CrawlerEmporium/5eCrawler#45]
What is the bug?: !class <name> level=None doesn't work anymore
Severity: High

- LordDusk#0001
Verification: 0

**Comment by crawltracker** [comment]
Note - LordDusk#0001

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(args, **kwargs)
  File "/root/5eCrawler/cogs5e/lookup.py", line 520, in _class
