### ISSUE TITLE
BUG-46 DB deity

### ISSUE THREAD

**Issue by crawltracker** [CrawlerEmporium/5eCrawler#62]
What is the bug?: DB deity

- LordDusk#0001
Verification: 0

**Comment by crawltracker** [comment]
Note - LordDusk#0001

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(args, **kwargs)
  File "/root/5eCrawler/cogs5e/dblookup.py", line 124, in db_deity
    await destination.send(embed=embed)
  File "/usr/local/lib/python3.7/site-packages/discord/abc.py", line 842, in send
    embed = embed.to_dict()
AttributeError: 'list' object has no attribute 'to_dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'list' object has no attribute 'to_dict'

**Comment by crawltracker** [comment]
Note - LordDusk#0001

Resolved - fixed
